### ISSUE TITLE
Are there any overlaps between VerSe '19 and '20?

### ISSUE THREAD

**Issue by kaimingkuang** [anjany/verse#1]
Hi,

I would like to use the VerSe dataset in our research for a novel segmentation method. Are there overlaps betwen '19 and '20? Does '20 include all data in '19? Thanks in advance.

**Comment by anjany** [comment]
Yes. There is an overlap between VerSe'19 and '20. No, not all of VerSe'19 in in '20. 

You can figure the common scans using their VerSe IDs. (if you want to use both, I recommend using the BIDS structure, so that the annotation-format is consistent)

**Comment by kleingeo** [comment]
In the restructured datasets for the Verse 2019 and 2020 datasets, what is the best way to determine what images overlap. I compared all filenames between the two datasets but found no matches. Do the files have a different naming structured for the same images?

**Comment by anjany** [comment]
By restructured, I imagine you mean the 'subject-based' ones?

**Comment by kleingeo** [comment]
Yes, I mean the subject based structured datasets from the OSF repos.

**Comment by anjany** [comment]
Sorry for the delay in response! Scans in VerSe'20 with an ID less than 500 are from VerSe'19. So, you can get the list of VerSe'20 scans from the MICCAI-version with scan-ID < 500, and download those IDs from the subject-based version of VerSe'19.

I realise this is a round-about way, and am working on making this easier. I'll update my response accordingly once that is ready.

**Comment by kleingeo** [comment]
I'm a little confused by that. Take sample `verse004` from the Verse 2020 Miccai set. This scan is also in the Verse 2019 Miccai set and in the subject based set (I'm assuming listed as `sub-verse004`). But how would I distinguish this scan in the Verse 2020 subject-based set?

**Comment by anjany** [comment]
You'd have to look for that in VerSe'19 (subject-based). Images in 'rawdata' and annotations in 'derivatives'.

**Comment by anjany** [comment]
Same filename. For example, for the example you have, this is the path: 

> dataset-verse19training/rawdata/sub-verse004

> dataset-verse19training/derivatives/sub-verse004

This becomes (relatively) easy once you have the IDs from VerSe20 (MICCAI) which are less than 500. Just look for these IDs in VerSe19 (subject)

**Comment by kleingeo** [comment]
Ok, but the issue I am having is that they do not seem to line up. There is no `sub-verse004` or `verse004` in the Verse 2020 subject-based dataset. There is a `sub-verse504` in the 2020 subject-based dataset. Is that what you are referring to by the less than 500? That seems to be the only potential match I can see, but the raw images themselves do not seem to be the same.

**Comment by anjany** [comment]
Did you check the VerSe'19 subject-base repo for it?

**Comment by kleingeo** [comment]
Yes, it is in that repo. But I thought the overlap would have it also in the 2020 subject-base repo as well.

**Comment by anjany** [comment]
No. Currently, the 'overlapped scans' are not in the subject-based repo of VerSe'20. You've to get them from VerSe'19.

**Comment by kleingeo** [comment]
Oh, ok. That's where my confusion is. So combining the subject-based data from the 2019 and 2020 means there should be no duplicates?

**Comment by anjany** [comment]
Exactly! :)

**Comment by kleingeo** [comment]
Thank you for clarifying.
