### ISSUE TITLE
ValueError: Not all axis codes [14, 286.58, 31.44, 217.16] in label set ['L', 'R', 'P', 'A', 'I', 'S', None]

### ISSUE THREAD

**Issue by AfsahS** [anjany/verse#2]
Hi,
I am willing to use verse 2020 data in the research project. However, there is an issue in processing data. Error is :

ValueError: Not all axis codes [14, 286.583921866619, 31.445132308242446, 217.1614294654032] in label set ['L', 'R', 'P', 'A', 'I', 'S', None].

Kindly let me know how to solve this issue?
TIA

**Comment by sainatarajan** [comment]
@AfsahS Have you solved this, and if yes, how did you do it?
