### ISSUE TITLE
How the coordinates of vertebrae centroids are labeled?

### ISSUE THREAD

**Issue by cloudpanl** [anjany/verse#4]
Hi，
Thank you for organizing and sharing the data. I am using VerSe'20 data. Can you tell me how the coordinates of vertebrae centroids are labeled? The MICCAI version or the subject-specific version is fine, I want to know how the coordinates of vertebrae centroids are annotated? Or what annotation software is used?

**Comment by anjany** [comment]
Please refer to #3. We can continue the conversation there.
