### ISSUE TITLE
Are Verse19 and Verse20 datasets compatible?

### ISSUE THREAD

**Issue by rijobro** [anjany/verse#8]
Thanks for the great datasets. I assume this to be true, but I can't see it mentioned anywhere explicitly so I wanted to check.

I downloaded the subject-based 19 and 20 datasets. Do the ground truth labels correspond between the two datasets? i.e., if a voxel in the 19 dataset has the value of 7, is it in the same vertebra as a voxel of value 7 in the 20 dataset?

Thanks for clearing this up for me.

**Comment by anjany** [comment]
Yes. A certain vertebra in the "real-world" (say C7) will always have the same label in all of VerSe (L1 <> label C7). You should see this information in the readme files of the OSF repositories (eg: https://osf.io/b2wxj/wiki/home/).
