### ISSUE TITLE
calculation of centroids

### ISSUE THREAD

**Issue by rijobro** [anjany/verse#9]
Hi, I want to be able to calculate the centroids of my network-inferred images. I'm struggling to re-create the ground truth centroids given by using the util functions. I added the following cell to the [evaluate.ipynb](https://github.com/anjany/verse/blob/main/utils/evaluate.ipynb) notebook and got differing results:

```python
for i in dutils.calc_centroids(true_msk):
    if i[0] != 0.0:  # skip background
        print(i)
    
for i in true_ctd:
    print(i)
```

results: 
```
('P', 'I', 'R')
[16.0, 91.0, 39.2, 63.4]
[17.0, 89.6, 62.6, 63.2]
[18.0, 85.4, 89.5, 62.9]
[19.0, 81.3, 119.3, 62.1]
[20.0, 77.7, 145.5, 61.2]
[21.0, 65.5, 171.2, 60.1]
[22.0, 59.3, 203.0, 58.3]
[23.0, 58.6, 233.7, 57.1]
[24.0, 66.7, 262.5, 56.9]

('P', 'I', 'R')
[16, 79.1, 40.9, 32.3]
[17, 79.3, 63.4, 32.2]
[18, 76.0, 88.6, 32.1]
[19, 70.6, 117.3, 31.6]
[20, 63.2, 141.9, 31.8]
[21, 53.0, 167.7, 30.8]
[22, 46.5, 202.0, 29.8]
[23, 46.8, 235.3, 29.1]
[24, 57.2, 266.4, 29.3]
```

Further, looking at a random image in the dataset, I don't even get the same number of non-zero labels:

```python
mask = "dataset-verse19validation/derivatives/sub-verse225/sub-verse225_seg-vert_msk.nii.gz"
gt_centroids = "dataset-verse19validation/derivatives/sub-verse225/sub-verse225_seg-vb_ctd.json"

print("Unique values in GT mask", np.unique(nib.load(mask).get_fdata()))
print("GT centroids", load_centroids(gt_centroids))
```
For which the output is:

```
Unique values in GT mask [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
GT centroids [('L', 'A', 'S'), [2, 82.4, 132.4, 123.6], [3, 83.2, 134.8, 103.9], [4, 84.3, 134.4, 87.8], [5, 85.9, 132.1, 72.3], [6, 87.1, 126.9, 56.4], [7, 88.6, 116.7, 42.0], [8, 90.9, 102.1, 29.1], [9, 93.3, 88.5, 15.3]]
```
Notice how the centroid for label 1 is missing in the ground truth centroids? This is despite the fact that in this particular image this label contains >13,000 voxels.

I'm pretty confused about how to be able to use this functionality in my code if I can't replicate using just ground truth data. Would you be able to clarify?

Thanks in advance.

**Comment by rijobro** [comment]
I realise this is a duplicate of https://github.com/anjany/verse/issues/3 so will close.

**Comment by dmus** [comment]
Any clarity here? I am facing the same issue
